In [1]:
from AquaML.data.DataUnit import DataUnit

a = DataUnit('test',(4,1))

ModuleNotFoundError: No module named 'AquaML'

In [2]:
a.create_shared_memory()

In [3]:
a.store(1,0)
a.store(2,1)

In [ ]:
a.close()

# Test data pool

In [1]:
from AquaML.data.DataPool import DataPool
from AquaML.DataType import DataInfo
from AquaML.data.DataUnit import DataUnit
import numpy as np

# create test data info

test_info = DataInfo(names=('test',),shapes=((4,1),),dtypes=np.float32)

test = DataPool(name='test', computer_type='PC', level=0)

test1_unit = DataUnit('test1',(4,1), level=0)


test.add_unit('test1', test1_unit)
test_info.add_info('test1', (4,1), np.float32)



test.multi_init(info_dic=test_info, type='buffer')

In [2]:
test_sub = DataPool(name='test', computer_type='PC', level=1)

sub_test1_unit = DataUnit('test1')
test_sub.add_unit('test1', sub_test1_unit)


test_sub.multi_init(info_dic=test_info, type='buffer')

In [3]:
test.data_pool['test1'].set_value(np.zeros((4,1))-0.5)

In [7]:
print(test_sub.get_unit('test1').buffer)

[[-0.5]
 [-0.5]
 [-0.5]
 [-0.5]]


In [5]:
test_sub.close()


In [2]:
from AquaML.rlalgo import SAC2

sac = SAC2()

ImportError: cannot import name 'BaseRLalgo' from partially initialized module 'AquaML.rlalgo.BaseRLAlgo' (most likely due to a circular import) (d:\和彩云同步文件夹\15150026836\AquaML\AquaML\rlalgo\BaseRLAlgo.py)

# Test

In [4]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
index_slice = slice(0, 2)

print(len(index_slice))
print(a[index_slice])
print(index_slice)

TypeError: object of type 'slice' has no len()

# concate

In [5]:
import numpy as np

a = [np.ones((4,1)), np.ones((3,1)), np.zeros((2,1))]

d = np.concatenate(a, axis=0)

print(d.shape)

(9, 1)


In [ ]:
import tensorflow as tf

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

print(optimizer.lr)

# model 测试

In [1]:
import tensorflow as tf

In [2]:
class Actor_net(tf.keras.Model):

    def __init__(self):
        super(Actor_net, self).__init__()

        self.lstm = tf.keras.layers.LSTM(32, input_shape=(2,), return_sequences=True, return_state=True)
        # if using batch time trajectory, return state must be True
        self.dense2 = tf.keras.layers.Dense(64)

        self.action_dense = tf.keras.layers.Dense(64)
        self.action_dense2 = tf.keras.layers.Dense(64)
        self.action_layer = tf.keras.layers.Dense(1, activation='tanh')

        self.value_dense = tf.keras.layers.Dense(64)
        self.value_dense2 = tf.keras.layers.Dense(64)
        self.value_layer = tf.keras.layers.Dense(1)

        self.leaky_relu = tf.keras.layers.LeakyReLU(alpha=0.2)

        # self.learning_rate = self.learning_rate = tf.keras.optimizers.schedules.ExponentialDecay(
        #     initial_learning_rate=0.01,
        #     decay_steps=1,
        #     decay_rate=0.9,
        #
        # )

        self.learning_rate = 2e-3

        self.rnn_flag = True

        self.output_info = {'action': (1,), 'fusion_value': (1,), 'hidden1': (32,), 'hidden2': (32,)}

        self.input_name = ('pos', 'hidden1', 'hidden2')

        self.optimizer = 'Adam'

    # @tf.function
    def call(self, vel, hidden1, hidden2):
        hidden_states = (hidden1, hidden2)
        whole_seq, last_seq, hidden_state = self.lstm(vel, hidden_states)
        x = self.dense2(whole_seq)
        x = self.leaky_relu(x)
        action_x = self.action_dense(x)
        action_x = self.leaky_relu(action_x)
        action_x = self.action_dense2(action_x)
        action_x = self.leaky_relu(action_x)
        action = self.action_layer(action_x)

        value_x = self.value_dense(x)
        value_x = self.leaky_relu(value_x)
        value_x = self.value_dense2(value_x)
        value_x = self.leaky_relu(value_x)
        value = self.value_layer(value_x)

        return (action, value, last_seq, hidden_state)

    def reset(self):
        pass

In [ ]:
model = Actor_net()

a = tf.ones((1, 20, 2))
hidden1 = tf.zeros((1, 32))

In [9]:
dense_model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(32),
    tf.keras.layers.Dense(64),
    tf.keras.layers.Dense(64),
    tf.keras.layers.Dense(1, activation='tanh')
])

b = tf.random.normal((6, 2))

c = tf.reshape(b, (1, 6, 2))
d = tf.reshape(b, (2, 3, 2))

print(b)

print(c)

print(d)

tf.Tensor(
[[ 0.7893334   2.5347073 ]
 [ 0.1579907   0.11265226]
 [-0.22426984  0.50227535]
 [ 0.06771586  0.5055766 ]
 [-0.6653793   2.1190336 ]
 [-1.166848   -0.30732048]], shape=(6, 2), dtype=float32)
tf.Tensor(
[[[ 0.7893334   2.5347073 ]
  [ 0.1579907   0.11265226]
  [-0.22426984  0.50227535]
  [ 0.06771586  0.5055766 ]
  [-0.6653793   2.1190336 ]
  [-1.166848   -0.30732048]]], shape=(1, 6, 2), dtype=float32)
tf.Tensor(
[[[ 0.7893334   2.5347073 ]
  [ 0.1579907   0.11265226]
  [-0.22426984  0.50227535]]

 [[ 0.06771586  0.5055766 ]
  [-0.6653793   2.1190336 ]
  [-1.166848   -0.30732048]]], shape=(2, 3, 2), dtype=float32)


In [11]:
print(dense_model(b))

tf.Tensor(
[[-0.30592903]
 [-0.013437  ]
 [-0.06442337]
 [-0.06339853]
 [-0.26435074]
 [ 0.03300342]], shape=(6, 1), dtype=float32)


In [12]:
print(dense_model(c))

tf.Tensor(
[[[-0.30592903]
  [-0.013437  ]
  [-0.06442337]
  [-0.06339853]
  [-0.26435074]
  [ 0.03300342]]], shape=(1, 6, 1), dtype=float32)


In [10]:
print(dense_model(d))

tf.Tensor(
[[[-0.30592903]
  [-0.013437  ]
  [-0.06442337]]

 [[-0.06339853]
  [-0.26435074]
  [ 0.03300342]]], shape=(2, 3, 1), dtype=float32)


In [15]:
import numpy as np

a = np.random.randint(0,10,1)
print(a)
print(type(a))
print(np.sort(a))

[3]
<class 'numpy.ndarray'>
[3]


In [18]:
print(np.append(1, a))

[1 3]


In [17]:
print(np.insert(a, 0, 1))

[1 3]


In [19]:
a = np.arange(9).reshape((3,3))

print(a.reshape(-1))

[0 1 2 3 4 5 6 7 8]


In [20]:
a = tf.ones((1, 2, 3))

print(a.shape)

(1, 2, 3)


In [24]:
print(tf.reshape(a, (-1)))

tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)
